apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dd3qb0yuk-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dd3qb0yuk-nodejs 
  name: dd3qb0yuk-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: dd3qb0yuk-nodejs 
